name: Run MLP Viewer

on:
  push:
    paths:
      - 'examples/mlp-viewer/**'
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: examples/mlp-viewer
        run: npm install

      - name: Run dev server
        working-directory: examples/mlp-viewer
        run: npm run dev
